jenkins:
    clouds:
      - docker:
          name: "docker"
          dockerApi:
            dockerHost:
              uri: "unix:///var/run/docker.sock"
          templates:
            - labelString: "docker-agent"
              dockerTemplateBase:
                image: "jenkins/slave"
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
              remoteFs: "/home/jenkins/agent"
              connector:
                attach:
                  user: "jenkins"
              instanceCapStr: "10"
              retentionStrategy:
                idleMinutes: 1